"""Helpers for locating and configuring Arduino CLI support."""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from .paths import _appdata_dir
from .platform_env import IS_WINDOWS


def find_arduino_cli(app_root: str | Path | None = None) -> str | None:
    """Locate arduino-cli binary across common Linux/Windows paths and PATH."""
    root = Path(app_root).resolve() if app_root is not None else Path(__file__).resolve().parent.parent

    local_names = ["arduino-cli.exe", "arduino-cli"] if IS_WINDOWS else ["arduino-cli"]
    for local_name in local_names:
        local_cli = root / "tools" / local_name
        if local_cli.is_file():
            return str(local_cli)

    cli = shutil.which("arduino-cli")
    if cli:
        return cli

    home = str(Path.home())
    candidates = [
        os.path.join(home, "bin", "arduino-cli"),
        "/usr/local/bin/arduino-cli",
        "/usr/bin/arduino-cli",
        r"C:\Program Files\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe",
        os.path.expandvars(
            r"%LOCALAPPDATA%\Programs\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe"
        ),
    ]
    env_cli = os.environ.get("ARDUINO_CLI")
    if env_cli:
        candidates.insert(0, env_cli)

    for candidate in candidates:
        if candidate and os.path.isfile(candidate):
            return candidate

    return None


def arduino_paths(base_dir: Path | None = None) -> dict[str, Path]:
    """Return MacroTouch-local Arduino directories and ensure they exist."""
    data_dir = (base_dir or _appdata_dir()) / "arduino-cli"
    sketchbook_dir = data_dir / "sketchbook"
    downloads_dir = data_dir / "downloads"
    libraries_dir = sketchbook_dir / "libraries"
    for path in (data_dir, sketchbook_dir, downloads_dir, libraries_dir):
        path.mkdir(parents=True, exist_ok=True)
    return {
        "data": data_dir,
        "sketchbook": sketchbook_dir,
        "downloads": downloads_dir,
        "libraries": libraries_dir,
    }


def ensure_arduino_cli_config(
    config_path: Path,
    data_dir: Path,
    sketchbook_dir: Path,
    downloads_dir: Path,
) -> None:
    """Write an isolated MacroTouch Arduino CLI config if needed."""
    content = (
        "# Auto-generated by MacroTouch\n"
        "directories:\n"
        f"  data: '{data_dir}'\n"
        f"  downloads: '{downloads_dir}'\n"
        f"  user: '{sketchbook_dir}'\n"
        "library:\n"
        "  enable_unsafe_install: true\n"
    )
    if config_path.exists():
        try:
            if config_path.read_text(encoding="utf-8") == content:
                return
        except Exception:
            pass
    config_path.write_text(content, encoding="utf-8")


def build_arduino_env(base_dir: Path | None = None) -> dict[str, str]:
    """Build environment variables for isolated Arduino CLI usage."""
    env = os.environ.copy()
    paths = arduino_paths(base_dir)
    config_path = paths["data"] / "arduino-cli.yaml"
    ensure_arduino_cli_config(
        config_path=config_path,
        data_dir=paths["data"],
        sketchbook_dir=paths["sketchbook"],
        downloads_dir=paths["downloads"],
    )
    env.setdefault("ARDUINO_DATA_DIR", str(paths["data"]))
    env.setdefault("ARDUINO_CONFIG_FILE", str(config_path))
    return env


def copy_bundled_library(app_root: str | Path, lib_name: str, base_dir: Path | None = None) -> bool:
    """Copy a bundled library into the isolated sketchbook directory."""
    src = Path(app_root) / "libraries" / lib_name
    if not src.exists():
        return False
    dest = arduino_paths(base_dir)["libraries"] / lib_name
    try:
        if dest.exists():
            shutil.rmtree(dest, ignore_errors=True)
        shutil.copytree(src, dest)
        return True
    except Exception:
        return False


def lovyangfx_ready(base_dir: Path | None = None) -> bool:
    """Return True if LovyanGFX exists and does not need the old ESP32 core patch."""
    lib_dir = arduino_paths(base_dir)["libraries"] / "LovyanGFX"
    if not lib_dir.exists():
        return False

    bus_rgb = lib_dir / "src" / "lgfx" / "v1" / "platforms" / "esp32s3" / "Bus_RGB.cpp"
    if not bus_rgb.exists():
        return True

    try:
        text = bus_rgb.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return True

    return (
        "gpio_hal_iomux_func_sel" not in text
        and "gpio_hal_func_sel(GPIO_PIN_MUX_REG" not in text
    )


def arduino_cli_run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    """Run Arduino CLI with hidden Windows console and captured text output."""
    run_kwargs = {"capture_output": True, "text": True, **kwargs}
    if IS_WINDOWS:
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = subprocess.SW_HIDE
        run_kwargs.setdefault("creationflags", subprocess.CREATE_NO_WINDOW)
        run_kwargs.setdefault("startupinfo", startupinfo)
    run_kwargs.setdefault("stdin", subprocess.DEVNULL)
    return subprocess.run(cmd, **run_kwargs)
